import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'
import {useSession} from "next-auth/react";

export default function Home() {
  const {data:session} = useSession();
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header user={session.user}></Header>
      </div>
    )


  }


